### ISSUE TITLE
学长请问还有资源吗

### ISSUE THREAD

**Issue by Patrickpwq** [Cowboy-Spike-Spiegel/BUPT_SCS_Resources#1]

**Comment by Patrickpwq** [comment]
只有一个README(；′⌒`)

**Comment by Cowboy-Spike-Spiegel** [comment]
有没有可能你在上边用main分支切换一下就找到了

**Comment by Cowboy-Spike-Spiegel** [comment]
在main分支里切换其他分支就可以

从 Windows 版邮件发送

发件人: Patrickpwq
发送时间: 2023年4月8日 11:59
收件人: Cowboy-Spike-Spiegel/BUPT_SCS_Resources
抄送: Subscribed
主题: Re: [Cowboy-Spike-Spiegel/BUPT_SCS_Resources] 学长请问还有资源吗 (Issue #1)

只有一个README(；′⌒`)

**Comment by Patrickpwq** [comment]
谢谢！
